// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTyCRqiZes6JKuShQAS_8nLAA8A858qUQ',
    appId: '1:652562513643:web:09bdcf001a02564491c8ae',
    messagingSenderId: '652562513643',
    projectId: 'appdevsem5-9535a',
    authDomain: 'appdevsem5-9535a.firebaseapp.com',
    storageBucket: 'appdevsem5-9535a.appspot.com',
    measurementId: 'G-1VY06WCT05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwvaBC5kxeE7b40sHObHg_u8EEtq7o7LY',
    appId: '1:652562513643:android:15e8ebb009ed9a3591c8ae',
    messagingSenderId: '652562513643',
    projectId: 'appdevsem5-9535a',
    storageBucket: 'appdevsem5-9535a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgHZK_1SoLrvALiU90nyPXQjgfV5SeaXs',
    appId: '1:652562513643:ios:84621530d33b98b491c8ae',
    messagingSenderId: '652562513643',
    projectId: 'appdevsem5-9535a',
    storageBucket: 'appdevsem5-9535a.appspot.com',
    iosBundleId: 'com.example.appDevAlumniConnectProjectSem5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgHZK_1SoLrvALiU90nyPXQjgfV5SeaXs',
    appId: '1:652562513643:ios:92f218b77347e42891c8ae',
    messagingSenderId: '652562513643',
    projectId: 'appdevsem5-9535a',
    storageBucket: 'appdevsem5-9535a.appspot.com',
    iosBundleId: 'com.example.appDevAlumniConnectProjectSem5.RunnerTests',
  );
}
